name: securewave_app
description: SecureWave Secure Messenger
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI и анимации
  cupertino_icons: ^1.0.6
  animations: ^2.0.10
  shimmer: ^3.0.0
  flutter_slidable: ^3.0.1
  mask_text_input_formatter: ^2.9.0
  
  # Сетевые запросы
  http: ^1.1.0
  dio: ^5.4.0
  web_socket_channel: ^2.4.0
  
  # Хранение данных
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Управление состоянием
  provider: ^6.1.1
  
  # Работа с медиа
  image_picker: ^1.0.5
  file_picker: ^6.1.1
  cached_network_image: ^3.3.1
  video_player: ^2.8.2
  
  # Утилиты
  intl: ^0.18.1
  timeago: ^3.6.0
  uuid: ^4.2.2
  crypto: ^3.0.3
  flutter_webrtc: ^1.2.0
  
  # Иконки и изображения
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  
  # Уведомления (для web)
  flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1



flutter:
  uses-material-design: true
  
  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
        - asset: fonts/NotoSans-Bold.ttf
          weight: 700
    
    # Добавляем fallback шрифты для специальных символов
    - family: NotoSansSymbols
      fonts:
        - asset: fonts/NotoSansSymbols-Regular.ttf
    
    - family: NotoEmoji
      fonts:
        - asset: fonts/NotoEmoji-Regular.ttf


  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
  
  # Удаляем секцию fonts полностью