// lib/firebase_options.dart
// File generated by FlutterFire CLI.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW5HurHMo1l9ub2XKyr2nk-yP22bc_6F4',
    appId: '1:394959992893:web:c7d493658ad06278661254',
    messagingSenderId: '394959992893',
    projectId: 'wave-messenger-56985',
    authDomain: 'wave-messenger-56985.firebaseapp.com',
    storageBucket: 'wave-messenger-56985.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn418sni1BuB_spzJmwZStW8va4WiI1NM',
    appId: '1:394959992893:android:63b18c66d1654eda661254',
    messagingSenderId: '394959992893',
    projectId: 'wave-messenger-56985',
    storageBucket: 'wave-messenger-56985.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlBnaWejApWZxll_oNko4s5bueSSbf9mg',
    appId: '1:394959992893:ios:5254ec3225b8e097661254',
    messagingSenderId: '394959992893',
    projectId: 'wave-messenger-56985',
    storageBucket: 'wave-messenger-56985.firebasestorage.app',
    iosBundleId: 'com.example.securewaveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlBnaWejApWZxll_oNko4s5bueSSbf9mg',
    appId: '1:394959992893:ios:5254ec3225b8e097661254',
    messagingSenderId: '394959992893',
    projectId: 'wave-messenger-56985',
    storageBucket: 'wave-messenger-56985.firebasestorage.app',
    iosBundleId: 'com.example.securewaveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW5HurHMo1l9ub2XKyr2nk-yP22bc_6F4',
    appId: '1:394959992893:web:014a01b2477a452d661254',
    messagingSenderId: '394959992893',
    projectId: 'wave-messenger-56985',
    authDomain: 'wave-messenger-56985.firebaseapp.com',
    storageBucket: 'wave-messenger-56985.firebasestorage.app',
  );
}
